### ISSUE TITLE
Using open source llm

### ISSUE THREAD

**Issue by Tortoise17** [MertKalkanci/Highlights-Maker#1]
Is it also possible to use open-source LLM with this workflow?

**Comment by MertKalkanci** [comment]
Yes you can use your own LLM with modifying ai.py,

**In default I've added Llama.cpp and OpenAI GPT support** but also you can add your own model via modifying the default functions that are there.

_Also I would be pleased if you contribute with the solution you will make. :)_

**Comment by MertKalkanci** [comment]
In the new version I've added fully llama.cpp support, you can use some .gguf formatted AI's via it, for more information on how to use it with llama.cpp please see `readme.md` and [Llama.cpp Github Page](https://github.com/ggerganov/llama.cpp)

**Comment by Tortoise17** [comment]
@MertKalkanci Billions of thank you. This is really a great help.
